# Generated by Django 2.1.7 on 2019-03-25 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=100)),
                ('component_type', models.IntegerField()),
                ('component_title', models.CharField(max_length=100)),
                ('component_creation_date', models.DateTimeField()),
                ('component_lastUpdate_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=100)),
                ('course_cecu', models.IntegerField()),
                ('course_category', models.IntegerField()),
                ('total_completion', models.IntegerField()),
                ('total_current_enrollment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic_pages.User')),
                ('autobiography', models.CharField(max_length=100)),
            ],
            bases=('basic_pages.user',),
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic_pages.User')),
                ('staffID', models.IntegerField()),
                ('obtained_cecu', models.IntegerField()),
                ('completed_course', models.CharField(max_length=100)),
            ],
            bases=('basic_pages.user',),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=100)),
                ('module_title', models.CharField(max_length=100)),
                ('module_complete', models.BooleanField()),
                ('module_progress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=100)),
                ('quiz_number_of_questions', models.IntegerField()),
                ('quiz_passingmark', models.IntegerField()),
                ('quiz_complete', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='dummy@dummy.com', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='fist_name',
            field=models.CharField(default='dummy', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='dummy', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='dummy', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic_pages.Component')),
                ('component_content', models.ImageField(upload_to='')),
            ],
            bases=('basic_pages.component',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic_pages.Component')),
                ('component_content', models.CharField(max_length=100)),
            ],
            bases=('basic_pages.component',),
        ),
    ]
