# Generated by Django 2.1.7 on 2019-03-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0002_auto_20190325_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basic_pages.Module'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='teachingCourse',
            field=models.ManyToManyField(to='basic_pages.Course'),
        ),
        migrations.AddField(
            model_name='learner',
            name='enrolled_course',
            field=models.ManyToManyField(to='basic_pages.Course'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basic_pages.Course'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basic_pages.Quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basic_pages.Module'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
