# Generated by Django 2.1.7 on 2019-03-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0003_auto_20190325_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_progress',
            field=models.IntegerField(),
        ),
    ]
