# Generated by Django 2.1.7 on 2019-03-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0004_auto_20190326_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
    ]
