# Generated by Django 2.1.7 on 2019-03-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0006_module_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='basic_pages.Course'),
        ),
    ]
