# Generated by Django 2.1.7 on 2019-03-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0007_auto_20190326_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
