# Generated by Django 2.1.7 on 2019-03-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0008_auto_20190326_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='basic_pages.Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='basic_pages.Module'),
        ),
    ]
