# Generated by Django 2.1.7 on 2019-03-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0014_auto_20190326_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
    ]
