# Generated by Django 2.1.7 on 2019-03-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0016_module_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_id',
        ),
    ]
