# Generated by Django 2.1.7 on 2019-03-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0017_auto_20190326_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_pages.Module'),
        ),
    ]
