# Generated by Django 2.1.7 on 2019-03-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0018_auto_20190326_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
