# Generated by Django 2.1.7 on 2019-03-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pages', '0020_auto_20190326_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='component_content',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='text',
            name='component_content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
